f:
  1:
    klass: "firewall"
    title: "Watchguard Simple Firewall"
    hacking_bonus: "0"
    botnet_bonus: "0"
    defense_bonus: "10"
    price: "250" 
  2:
    klass: "firewall"
    title: "Watchguard Standard Firewall"
    hacking_bonus: "0"
    botnet_bonus: "0"
    defense_bonus: "20"
    price: "500"
  3:
    klass: "firewall"
    title: "Watchguard Expert Firewall"
    hacking_bonus: "0"
    botnet_bonus: "0"
    defense_bonus: "35"
    price: "875"
  4:
    klass: "firewall"
    title: "Watchguard Ultimate Firewall"
    hacking_bonus: "0"
    botnet_bonus: "0"
    defense_bonus: "50"
    price: "1250"
c:
  1:
    klass: "compiler"
    title: "Standard C-Compiler"
    hacking_bonus: "10"
    botnet_bonus: "0"
    defense_bonus: "0"
    price: "350"
  2:
    klass: "compiler"
    title: "C-Compiler with Preprocessor"
    hacking_bonus: "15"
    botnet_bonus: "0"
    defense_bonus: "0"
    price: "550"
  3:
    klass: "compiler"
    title: "Prefetch-Compiler"
    hacking_bonus: "25"
    botnet_bonus: "0"
    defense_bonus: "0"
    price: "875"
  4:
    klass: "compiler"
    title: "Intelligent HAL-Compiler"
    hacking_bonus: "40"
    botnet_bonus: "0"
    defense_bonus: "0"
    price: "1500"
  5:
    klass: "compiler"
    title: "BioFlop-Compiler"
    hacking_bonus: "65"
    botnet_bonus: "0"
    defense_bonus: "0"
    price: "2375"
b:
  1:
    klass: "botnet"
    title: "Smoke-Botnet"
    hacking_bonus: "0"
    botnet_bonus: "10"
    defense_bonus: "0"
    price: "300"
  2:
    klass: "botnet"
    title: "Scramble-Botnet"
    hacking_bonus: "0"
    botnet_bonus: "25"
    defense_bonus: "0"
    price: "750"
  3:
    klass: "botnet"
    title: "Andariel-Botnet"
    hacking_bonus: "0"
    botnet_bonus: "50"
    defense_bonus: "0"
    price: "1600"
  4:
    klass: "botnet"
    title: "Starkiller-Botnet"
    hacking_bonus: "0"
    botnet_bonus: "60"
    defense_bonus: "0"
    price: "1950"
m:
  1:
    klass: "utility"
    title: "Intrusion Detection System"
    price: "8400"